name: 'flyMS Docker Environment'
description: 'Runs commands in the Dockerized flyMS build environment' '
runs:
  using: 'docker'
  image: '../../docker/Dockerfile'
  args:
    - --source-dir
    - /github/workspace