name: Workflow for flyMS

on: [push]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  flyMS_build_and_tests:
    runs-on: ubuntu-latest
    name: flyMS build and tests

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: ./flyMS_build.sh -b --test
      - run: ./flyMS_build.sh -b

      #Github pages
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload from the sphinx directory
          path: './build/docs/sphinx/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      # - name: Build and run unit tests
      #   uses: ./.github/actions/ # Uses an action in this directory
      #   # id: flyMS_Docker_Environment
      #   with:
      #     build_and_run_unit_tests: '--test'
      # - name: Cross Compile
      #   uses: ./.github/actions/
      #   # id: flyMS_Docker_Environment